name: Test Building vAccel

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.archconfig }}", rust ]

    strategy:
      matrix:
        archconfig: [x86_64, aarch64, armv7l]
        build_type: [debug, release]
      fail-fast: false

    steps:
    - name: Find SHA
      run: |
        if [[ "${{github.event.pull_request.head.sha}}" != "" ]]
        then
          echo "ARTIFACT_SHA=$(echo ${{github.event.pull_request.head.sha}})" >> $GITHUB_ENV
        else
          echo "ARTIFACT_SHA=$(echo ${{github.sha}})" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build agent
      run: |
        if [[ ${{matrix.build_type}} == "release" ]]
        then
          cargo build --release -j $(nproc)
        else
          cargo build -j $(nproc)
        fi
        mkdir -p binary
        cp target/${{matrix.build_type}}/vaccelrt-agent ./binary

    - name: Upload artifact by name
      if: ${{ env.ARTIFACT_NAME == 'main' || env.ARTIFACT_NAME == 'master' }}
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: binary/vaccelrt-agent
        remote-path: nbfc-assets/github/vaccelrt/agent/${{env.ARTIFACT_NAME}}/${{matrix.archconfig}}/${{matrix.build_type}}/
        policy: 1

    - name: Upload artifact
      uses: cloudkernels/minio-upload@v4
      with:
        url: https://s3.nubificus.co.uk
        access-key: ${{ secrets.AWS_ACCESS_KEY }}
        secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        local-path: binary/vaccelrt-agent
        remote-path: nbfc-assets/github/vaccelrt/agent/${{env.ARTIFACT_SHA}}/${{matrix.archconfig}}/${{matrix.build_type}}/
