name: Test Building bindings

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, "${{ matrix.archconfig }}"]

    strategy:
      matrix:
        archconfig: [x86_64, aarch64]
        build_type: [debug, release]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install deps
      run: |
        sudo apt-get update && \
        sudo apt-get install -y cmake

    - name: Cargo hack
      run: |
        sudo chmod a+w /opt/cargo -R

    - name: Build bindings
      run: |
        if [[ ${{matrix.build_type}} == "release" ]]
        then
          cargo build --release
        else
          cargo build
        fi
