[package]
name = "vsock"
version = "0.3.2"
authors = ["Babis Chalios <mail@bchalios.io>", "Kostis Papazafeiropoulos <papazof@gmail.com>", "Anastassios Nanos <ananos@nubificus.co.uk>" ]
edition = "2021"
license = "Apache-2.0"

[lib]
name = "vaccel_vsock"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
protocols = { git = "https://github.com/nubificus/vaccel-grpc.git", tag = "v0.3.4" }
vaccel = { git = "https://github.com/nubificus/vaccel-bindings.git", tag = "v0.5.3" }
ttrpc = { git = "https://github.com/nubificus/ttrpc-rust.git", tag = "v0.6.1-vaccel" }
protobuf = "2.27.1"
nix = "0.24.1"
