[package]
name = "vsock"
version = "0.3.5"
authors = ["Babis Chalios <mail@bchalios.io>", 
           "Kostis Papazafeiropoulos <papazof@gmail.com>", 
           "Anastassios Nanos <ananos@nubificus.co.uk>", 
           "Shenghao Qiu <shenghao@nubificus.co.uk"]
edition = "2021"
license = "Apache-2.0"

[lib]
name = "vaccel_vsock"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
protocols = { git = "https://github.com/nubificus/vaccel-grpc.git", tag = "v0.3.5" }
vaccel = { git = "https://github.com/nubificus/vaccel-bindings.git", tag = "v0.5.5" }
ttrpc = { git = "https://github.com/nubificus/ttrpc-rust.git", tag = "v0.6.1-vaccel-1" }
protobuf = "2.28.0"
nix = "0.24.1"
libc = "0.2"
