[package]
name = "vsock"
version = "0.1.0"
authors = ["Babis Chalios <mail@bchalios.io>"]
edition = "2018"

[lib]
name = "vaccel_vsock"
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
protocols = { git = "https://github.com/cloudkernels/vaccel-grpc.git", branch = "feat_tf_inference" }
vaccel = { git = "https://github.com/cloudkernels/vaccel-bindings.git", branch = "refactor_api" }
vm-memory = { version = ">=0.2.2" }

protobuf = "2.14.0"
ttrpc = { git = "https://github.com/cloudkernels/ttrpc-rust.git", branch = "devel" }
anyhow = "1.0.31"
nix = "0.17.0"
libc = "0.2.69"
