// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `error.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:vaccel.VaccelError)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct VaccelError {
    // message oneof groups
    pub error: ::std::option::Option<vaccel_error::Error>,
    // special fields
    // @@protoc_insertion_point(special_field:vaccel.VaccelError.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a VaccelError {
    fn default() -> &'a VaccelError {
        <VaccelError as ::protobuf::Message>::default_instance()
    }
}

impl VaccelError {
    pub fn new() -> VaccelError {
        ::std::default::Default::default()
    }

    // int64 vaccel_error = 1;

    pub fn vaccel_error(&self) -> i64 {
        match self.error {
            ::std::option::Option::Some(vaccel_error::Error::VaccelError(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_vaccel_error(&mut self) {
        self.error = ::std::option::Option::None;
    }

    pub fn has_vaccel_error(&self) -> bool {
        match self.error {
            ::std::option::Option::Some(vaccel_error::Error::VaccelError(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_vaccel_error(&mut self, v: i64) {
        self.error = ::std::option::Option::Some(vaccel_error::Error::VaccelError(v))
    }

    // int64 agent_error = 2;

    pub fn agent_error(&self) -> i64 {
        match self.error {
            ::std::option::Option::Some(vaccel_error::Error::AgentError(v)) => v,
            _ => 0,
        }
    }

    pub fn clear_agent_error(&mut self) {
        self.error = ::std::option::Option::None;
    }

    pub fn has_agent_error(&self) -> bool {
        match self.error {
            ::std::option::Option::Some(vaccel_error::Error::AgentError(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_agent_error(&mut self, v: i64) {
        self.error = ::std::option::Option::Some(vaccel_error::Error::AgentError(v))
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "vaccel_error",
            VaccelError::has_vaccel_error,
            VaccelError::vaccel_error,
            VaccelError::set_vaccel_error,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_copy_has_get_set_simpler_accessors::<_, _>(
            "agent_error",
            VaccelError::has_agent_error,
            VaccelError::agent_error,
            VaccelError::set_agent_error,
        ));
        oneofs.push(vaccel_error::Error::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<VaccelError>(
            "VaccelError",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for VaccelError {
    const NAME: &'static str = "VaccelError";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                8 => {
                    self.error = ::std::option::Option::Some(vaccel_error::Error::VaccelError(is.read_int64()?));
                },
                16 => {
                    self.error = ::std::option::Option::Some(vaccel_error::Error::AgentError(is.read_int64()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.error {
            match v {
                &vaccel_error::Error::VaccelError(v) => {
                    my_size += ::protobuf::rt::int64_size(1, v);
                },
                &vaccel_error::Error::AgentError(v) => {
                    my_size += ::protobuf::rt::int64_size(2, v);
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.error {
            match v {
                &vaccel_error::Error::VaccelError(v) => {
                    os.write_int64(1, v)?;
                },
                &vaccel_error::Error::AgentError(v) => {
                    os.write_int64(2, v)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> VaccelError {
        VaccelError::new()
    }

    fn clear(&mut self) {
        self.error = ::std::option::Option::None;
        self.error = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static VaccelError {
        static instance: VaccelError = VaccelError {
            error: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for VaccelError {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("VaccelError").unwrap()).clone()
    }
}

impl ::std::fmt::Display for VaccelError {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VaccelError {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `VaccelError`
pub mod vaccel_error {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:vaccel.VaccelError.error)
    pub enum Error {
        // @@protoc_insertion_point(oneof_field:vaccel.VaccelError.vaccel_error)
        VaccelError(i64),
        // @@protoc_insertion_point(oneof_field:vaccel.VaccelError.agent_error)
        AgentError(i64),
    }

    impl ::protobuf::Oneof for Error {
    }

    impl ::protobuf::OneofFull for Error {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::VaccelError as ::protobuf::MessageFull>::descriptor().oneof_by_name("error").unwrap()).clone()
        }
    }

    impl Error {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Error>("error")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0berror.proto\x12\x06vaccel\"^\n\x0bVaccelError\x12#\n\x0cvaccel_err\
    or\x18\x01\x20\x01(\x03H\0R\x0bvaccelError\x12!\n\x0bagent_error\x18\x02\
    \x20\x01(\x03H\0R\nagentErrorB\x07\n\x05errorb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(VaccelError::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
