[package]
name = "protocols"
version = "0.1.0"
authors = ["Babis Chalios <mail@bchalios.io>"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttrpc = { git = "https://github.com/cloudkernels/ttrpc-rust.git", branch = "devel" }
protobuf = "=2.14.0"

[build-dependencies]
ttrpc-codegen = "0.2"
