[package]
name = "protocols"
version = "0.1.0"
authors = ["Babis Chalios <mail@bchalios.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ttrpc = "0.3.0"
protobuf = "=2.14.0"

[build-dependencies]
ttrpc-codegen = "0.1.2"
