name: Build and Upload

on:
  push:
    branches: [main]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-dist:
    name: Build and Upload
    uses: nubificus/vaccel/.github/workflows/verify-build.yml@main
    with:
      release: true
      runner: '["base", "dind", "2204"]'
      package: 'rust'
      options: 'rpc-client=enabled,rpc-agent=enabled'
      upload-subpath: 'rust'
    secrets: inherit
