[package]
name = "vaccelrt-agent"
version = "0.1.0"
authors = ["Babis Chalios <mail@bchalios.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocols = { path = "vaccel-grpc" }
ttrpc = "0.3.0"
protobuf = "=2.14.0"
serde_json = "1.0.39"
vaccel-bindings = { git = "https://github.com/bchalios/vaccel-bindings", branch = "master" }
signal-hook = "0.1.9"
ctrlc = { version = "3.0", features = ["termination"] }

[workspace]
members = [
	"vaccel-grpc"
]
