[package]
name = "vaccelrt-agent"
version = "0.2.0"
authors = ["Nubificus Ltd"]
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocols = { git = "https://github.com/cloudkernels/vaccel-grpc.git", branch = "feat_genop" }
ttrpc = { git = "https://github.com/cloudkernels/ttrpc-rust.git", tag = "vaccel-0.1.0" }
protobuf = "=2.14.0"
serde_json = "1.0.39"
vaccel = { git = "https://github.com/cloudkernels/vaccel-bindings", branch = "feat_genop" }
signal-hook = "0.1.9"
ctrlc = { version = "3.0", features = ["termination"] }
structopt = { version = "0.3", default-features = false }
chashmap = { version = "2.2.0" }
