[package]
name = "vaccelrt-agent"
version = "0.1.0"
authors = ["Babis Chalios <mail@bchalios.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocols = { git = "https://github.com/cloudkernels/vaccel-grpc.git", tag = "v0.1.0" }
ttrpc = { git = "https://github.com/cloudkernels/ttrpc-rust.git", branch = "devel" }
protobuf = "=2.14.0"
serde_json = "1.0.39"
vaccel = { git = "https://github.com/cloudkernels/vaccel-bindings", tag = "v0.1.1" }
signal-hook = "0.1.9"
ctrlc = { version = "3.0", features = ["termination"] }
structopt = { version = "0.3", default-features = false }
chashmap = { version = "2.2.0" }
